server:
  port: 8092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchangeadak
    username: arvin_z
    password: 856921
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true